module.exports = [
  {
    title: "HVDC Grids: For Offshore and Super grid of Future",
    author: "Hertem D. V.",
    publisher: "Wiley",
    subject: "Physical Sciences & Engineering",
    year: 2016,
    location: "624.27",
  },
  {
    title: "“Classical” Algebraic K-Theory, and Connections with Arithmetic",
    author: "H. Bass",
    publisher: "Springer",
    subject: "Mathematics",
    year: 1973,
    location: "112.234",
  },
  {
    title: "1-Dimensional Cohen-Macaulay Rings",
    author: "Eben Matlis",
    publisher: "Springer",
    subject: "Mathematics",
    year: 1973,
    location: "112.236",
  },
  {
    title: "100 Questions (and Answers) About Action Research",
    author: "Luke Duesbery",
    publisher: "SAGE Publications Ltd",
    subject: "Action Research",
    year: 2020,
    location: "234.456",
  },
  {
    title: "18 Brand Astra",
    author: "Jagdeep Kapoor",
    publisher: "SAGE",
    subject: "Business & Management; Advertising & Promotion",
    year: 2015,
    loaction: "423.56",
  },
];
